-- MySQL Script generated by MySQL Workbench
-- Thu Sep  4 09:03:24 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lumlogisticdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lumlogisticdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lumlogisticdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `lumlogisticdb` ;

-- -----------------------------------------------------
-- Table `lumlogisticdb`.`shelf_life`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`shelf_life` (
  `id_shelf_life` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `concept` VARCHAR(100) NOT NULL,
  `duration` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_shelf_life`))
ENGINE = InnoDB
AUTO_INCREMENT = 79
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`catalog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`catalog` (
  `id_product` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ean` VARCHAR(50) NOT NULL,
  `sync_id` INT(10) UNSIGNED NOT NULL,
  `vivo_id` INT(10) UNSIGNED NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `block_status` VARCHAR(100) NOT NULL,
  `image_url` VARCHAR(255) NULL DEFAULT NULL,
  `id_shelf_life` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_product`),
  INDEX `idx_catalog_ean` (`ean` ASC),
  INDEX `idx_catalog_sync_id` (`sync_id` ASC),
  INDEX `fk_catalog_shelf_life` (`id_shelf_life` ASC),
  CONSTRAINT `fk_catalog_shelf_life`
    FOREIGN KEY (`id_shelf_life`)
    REFERENCES `lumlogisticdb`.`shelf_life` (`id_shelf_life`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23741
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`cities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`cities` (
  `id_city` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_city`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`roles` (
  `id_role` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  `role_description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`stores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`stores` (
  `id_store` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_name` VARCHAR(150) NOT NULL,
  `store_address` VARCHAR(255) NOT NULL,
  `store_email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `id_role` INT(10) UNSIGNED NOT NULL DEFAULT 3,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `last_login` DATETIME NULL DEFAULT NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `city_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_store`),
  UNIQUE INDEX `store_email` (`store_email` ASC),
  INDEX `fk_store_role` (`id_role` ASC),
  INDEX `fk_stores_city` (`city_id` ASC),
  CONSTRAINT `fk_store_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `lumlogisticdb`.`roles` (`id_role`)
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stores_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `lumlogisticdb`.`cities` (`id_city`))
ENGINE = InnoDB
AUTO_INCREMENT = 70
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`store_stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`store_stock` (
  `id_stock` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_store` INT(10) UNSIGNED NOT NULL,
  `id_product` INT(10) UNSIGNED NOT NULL,
  `chipperprice` INT(11) NULL DEFAULT NULL,
  `total_stock` INT(11) NOT NULL DEFAULT 0,
  `sync_id` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_stock`),
  UNIQUE INDEX `uniq_store_product` (`id_store` ASC, `id_product` ASC),
  INDEX `fk_stock_product` (`id_product` ASC),
  CONSTRAINT `fk_stock_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `lumlogisticdb`.`catalog` (`id_product`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_stock_store`
    FOREIGN KEY (`id_store`)
    REFERENCES `lumlogisticdb`.`stores` (`id_store`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`users` (
  `id_user` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `id_role` INT(10) UNSIGNED NOT NULL,
  `is_active` TINYINT(1) NULL DEFAULT 1,
  `google_id` VARCHAR(50) NULL DEFAULT NULL,
  `profile_picture_url` VARCHAR(255) NULL DEFAULT NULL,
  `provider` ENUM('local', 'google') NULL DEFAULT 'local',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `last_login` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email` (`email` ASC),
  UNIQUE INDEX `google_id` (`google_id` ASC),
  INDEX `fk_user_role` (`id_role` ASC),
  CONSTRAINT `fk_user_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `lumlogisticdb`.`roles` (`id_role`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `lumlogisticdb`.`validation_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lumlogisticdb`.`validation_history` (
  `id_validation` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ean` VARCHAR(50) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `expiration_date` DATE NOT NULL,
  `block_date` DATE NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `category` VARCHAR(100) NOT NULL,
  `days_lifespan` INT(11) NULL DEFAULT NULL,
  `block_concept` VARCHAR(100) NOT NULL,
  `remarks` VARCHAR(255) NULL DEFAULT NULL,
  `id_store` INT(10) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_validation`),
  INDEX `idx_history_ean` (`ean` ASC),
  INDEX `idx_history_expiration` (`expiration_date` ASC),
  INDEX `fk_history_store` (`id_store` ASC),
  CONSTRAINT `fk_history_store`
    FOREIGN KEY (`id_store`)
    REFERENCES `lumlogisticdb`.`stores` (`id_store`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
